# Generated by Django 4.2.21 on 2025-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cashflowrecord',
            name='date',
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='status',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
