# Generated by Django 4.2.21 on 2025-05-25 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AlterModelOptions(
            name='cashflowrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflowrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cashflow.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.type'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.category'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.status'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cashflow.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.type'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('type', 'name')},
        ),
    ]
